### ISSUE TITLE
Remove / rename `master` branch when new site is released

### ISSUE THREAD

**Issue by ColeKettler** [PublicMapping/publicmapping.github.com#8]
The source in the `master` branch maintains a redirect from https://publicmapping.github.io to https://publicmapping.github.io/districtbuilder/. Once we have an initial release for the new version of the site ready, we should either:

- remove the `master` branch in favor of using the `main` branch, which is the production branch for the new site on Netlify
- rename the `master` branch to something else that GItHub pages will build (e.g. `gh-pages`) provided that we want to maintain the old site redirect for some period of time.

**Comment by hectcastro** [comment]
I renamed the `master` branch to `archive`. I don't expect that we'll need it or any form of redirect moving forward though.
